### ISSUE TITLE
Recent Updates section list filter, top N

### ISSUE THREAD

**Issue by petermezei** [slamby/slamby-developers#4]
Developers Site index page,

right now under the recent updates section we display all the updates, but after a while its going to be too long. We should implement a top N filter, displaying just the top N results. I suggest to display the top 10 news.

+ set a link, to the all news page. Suggested link/button name "Read all", that directs to the all updates page.

![image](https://cloud.githubusercontent.com/assets/18461114/22013188/155f4caa-dc98-11e6-9c9b-8dd2943dd2d4.png)

**Comment by attilalaszlo** [comment]
What about the design? Is it OK for now?

**Comment by petermezei** [comment]
for now its ok.
One thing: lets write the year in dates too.
